theme: jekyll-theme-slate
title: 1,2,3, Durable
description: Le projet "1,2,3, Durable!" est une initiative du conseil de quartier Croix Rousse Centre qui vise à accélérer la mise en place d'actions en faveur du développement durable dans le 4ème arrondissement de Lyon.
