theme: jekyll-theme-slate
title: 1,2,3, Durable
description: Le projet 1,2,3 Durable! est issu du conseil de quartier Croix Rousse Centre et vise à accélérer la mise en place d'actions en faveur du développement durable dans le 4eme arrondissement de Lyon
